CREATE OR REPlACE PROCEDURE INSERT_PLANT_CALIBRATED_SENSOR (p_plant_id IN PLANT_CALIBRATED_SENSOR.PLANT_ID%TYPE,
                                                        p_calibrated_sensor_id IN PLANT_CALIBRATED_SENSOR.CALIBRATED_SENSOR_ID%TYPE
)
    IS
BEGIN
    INSERT INTO PLANT_CALIBRATED_SENSOR ("PLANT_ID", "CALIBRATED_SENSOR_ID")
    VALUES (p_plant_id, p_calibrated_sensor_id);
    COMMIT;
END INSERT_PLANT_CALIBRATED_SENSOR;