CREATE OR REPlACE PROCEDURE DROP_TABLES
    IS
BEGIN
    DROP TABLE SENSOR_ACTUATOR CASCADE CONSTRAINTS;
    DROP TABLE PLANT_STATIC_SENSOR CASCADE CONSTRAINTS;
    DROP TABLE PLANT_CALIBRATED_SENSOR CASCADE CONSTRAINTS;
    DROP TABLE PLANT CASCADE CONSTRAINTS;
    DROP TABLE SENSOR CASCADE CONSTRAINTS;
    DROP TABLE STATIC_SENSOR CASCADE CONSTRAINTS;
    DROP TABLE CALIBRATED_SENSOR CASCADE CONSTRAINTS;
    DROP TABLE "USER" CASCADE CONSTRAINTS;
    DROP TABLE ACTUATOR CASCADE CONSTRAINTS;
    DROP TABLE ENVIRONMENT CASCADE CONSTRAINTS;
END DROP_TABLES;
